services:
  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=ecom_ms
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "auth"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: on-failure
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 5050:80
  #     - 5051:443

  inventory_service:
    build:
      context: ./services/inventory
      dockerfile: Dockerfile
    env_file:
      - ./services/inventory/.env
    ports:
      - 4002:4002
    volumes:
      - ./services/inventory:/app
    command: yarn run dev

volumes:
  postgres:
